#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jan 31 01:16:55 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
